### ISSUE TITLE
Unable to create screenshot storage directory.

### ISSUE THREAD

**Issue by JoseAlcerreca** [dropbox/dropshots#14]
I'm still investigating this, but I bumped Dropshot from 0.1.1 to 0.2.0 and everything worked great. I was able to record and run.

Then I removed the WRITE_EXTERNAL_STORAGE permission from the module's manifest as it's no longer required and I started getting the error.

I added the permission again and I still see the same error. I tried cleaning, etc.

**Comment by JoseAlcerreca** [comment]
Update: Ran them on an API 30 emulator and worked fine. 

28 still crashing with "Unable to create screenshot storage directory."

**Comment by rharter** [comment]
I ran into this yesterday and have a local fix in place that I'll submit a
PR for next week. The issue appears to be that while permissions aren't
required to write to the Downloads directory on API 29+, they are required
for API <= 28.  My fix just wraps dropshots in the grant permissions rule
if API <= 28.

**Comment by findjigar** [comment]
I get this `java.lang.IllegalStateException: Unable to create screenshot storage directory.` on API 29 emulator `("system-images;android-29;default;x86"
)`. Should I add `WRITE_EXTERNAL_STORAGE` permission in manifest?

**Comment by findjigar** [comment]
Update: It works with `system-images;android-30;default;x86_64` image

**Comment by sergio-sastre** [comment]
> I get this `java.lang.IllegalStateException: Unable to create screenshot storage directory.` on API 29 emulator `("system-images;android-29;default;x86" )`. Should I add `WRITE_EXTERNAL_STORAGE` permission in manifest?
> 
> It only happens on `CircleCI` but works fine on-device locally

Same here :(
