### ISSUE TITLE
Allow to save screenshots in folders

### ISSUE THREAD

**Issue by sebastienrouif** [dropbox/dropshots#24]
On top of the file name it would be great to be able to store the screenshots into folders.
I currently end up with hundreds of view screenshots and some names get truncated because they are too long. Having folders would allow more nested structure and would avoid prefix in file names
Happy to contribute if you agree with the feature

**Comment by sebastienrouif** [comment]
Is that something you would be interested in, I might put the time to contribute later on as the number of screenshot is growing on my side

**Comment by rharter** [comment]
That sounds like a great feature to me. A contribution would be great!

**Comment by sebastienrouif** [comment]
added feature in https://github.com/dropbox/dropshots/pull/35

**Comment by antonio-pedro99** [comment]
Hey @rharter this issue as been fixed in PR #35 which is now closed! Could you please close this issue as well?

**Comment by rharter** [comment]
Huh, I figured the or would close the issue. Here we go!
