### ISSUE TITLE
Missing Custom Validation

### ISSUE THREAD

**Issue by mtomczynski** [dropbox/dropshots#28]
Hey,

there's a section in README about custom validation with objects like `ResultValidator`, `CountValidator` and `ThresholdValidator`. But it seems that the Dropshots API is missing those elements in my project (ver `0.3.0`), could you please add a sample or small snippet on how to use that feature?

**Comment by rharter** [comment]
That's not released yet, so you'll need to use a snapshot version to access
it.

**Comment by rharter** [comment]
This is available in 0.4.0 on Maven Central.
