### ISSUE TITLE
Storage permission fix for API 29

### ISSUE THREAD

**Issue by JayShortway** [dropbox/dropshots#32]
Hi,

Thanks for creating this useful tool! I really appreciate the fact that `assertSnapshot()` accepts a direct Bitmap as well, as that's more fitting for my use case than a View or Activity. 

**Issue**  
I had some issues getting this to work with my Android 10 (API 29) device. The runtime library is unable to write to the Downloads folder.

To my understanding, Android 10 is a bit of a special case in terms of scoped storage. It's the first version with scoped storage, but it doesn't have the [direct file paths](https://developer.android.com/training/data-storage/shared/media#direct-file-paths) feature yet, introduced in Android 11, which re-enables the use of the Java File API.

**Fix**  
So on Android 10, if an app wants to write to a media folder such as Downloads, it has 2 options: 
- it either needs to use the [MediaStore API](https://developer.android.com/training/data-storage/shared/media#media_store), or 
- it needs to set [`requestLegacyExternalStorage`](https://developer.android.com/reference/kotlin/android/R.attr#requestLegacyExternalStorage:kotlin.Int) to `true` and declare the [`WRITE_EXTERNAL_STORAGE`](https://developer.android.com/training/data-storage/shared/media#extra-permissions) permission if it wants to use the Java File API.

**Accepting PRs?**  
I have the second option implemented in a local checkout of Dropshots and it's working well. Would you like me to create a pull request? I'd be happy to!

**Comment by findjigar** [comment]
I recently commented on related past issue about API 29: https://github.com/dropbox/dropshots/issues/14

**Comment by JayShortway** [comment]
@findjigar Ah I see. You should be able to fix it in your project by doing these 2 things: 

1. Add this to `src/androidTest/AndroidManifest.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
    ...
    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        android:maxSdkVersion="29"
        tools:node="replace" />

    <application
        android:requestLegacyExternalStorage="true"
        tools:node="merge" />
    ...
</manifest>
```
2. Add this to your test class:
```kotlin
@get:Rule
val grantPermission = GrantPermissionRule.grant(Manifest.permission.WRITE_EXTERNAL_STORAGE)
```  
  
Let me know if this works for you!

**Comment by findjigar** [comment]
@JayShortway I already had the manifest changes but missed the `GrantPermissionRule`. That fixed the tests on my side with API-29. Thanks.

**Comment by JayShortway** [comment]
@findjigar Great, happy to help! (Regarding the typo: you can `import android.Manifest` as well.)

**Comment by sergio-sastre** [comment]
> 

Please, create a PR! 
I'm sure @rharter would appreciate it :)

**Comment by JayShortway** [comment]
@sergio-sastre @rharter Alright :) I opened a PR here: https://github.com/dropbox/dropshots/pull/34  
Let me know if you have any comments or questions.
