### ISSUE TITLE
depend on android.library?

### ISSUE THREAD

**Issue by digitalbuddha** [dropbox/dropshots#4]
My gradle fu is not great but was wondering if it is possible to not have to apply android.library/android.app plugin before dropshots. Maybe there is an api that can check if it is on path rather than requiring ordering?

**Comment by digitalbuddha** [comment]
example of test execution:
gradlew :myApp:myModule-sandbox:installDebug :myApp:myModule-sandbox:installDebugAndroidTest && adb shell am instrument -w com.twitter.sandbox.notifications.push.test/androidx.test.runner.AndroidJUnitRunner

**Comment by rharter** [comment]
Fixed in a2aa635
