### ISSUE TITLE
decouple pulling screenshots from android testing task

### ISSUE THREAD

**Issue by digitalbuddha** [dropbox/dropshots#5]
This is more of a question - do i have to use cAT to get the record screenshot api? There's a use case I am dealing with where tests are running using the instrumentation api directly

**Comment by rharter** [comment]
You should be able to use `pullDebugScreenshots` or `updateDebugScreenshots` tasks (replace `Debug` with your variant of choice) to either pull the screenshots into the test report directory or the reference image directory, respectively.

**Comment by digitalbuddha** [comment]
Thank you 🙏
