### ISSUE TITLE
[Question] Any plans for snapshot diff?

### ISSUE THREAD

**Issue by vojtech-cerveny** [dropbox/dropshots#50]
Hey, 
I want to ask, if you have any **plans** for showing diff of screenshots if diff is there. It would be nice to create for example new folder `/diff` and store diffs there.

I am not sure if this is possible by your approach.

**Comment by JayShortway** [comment]
Hi @vojtech-cerveny, 

In case of a failing test, diff images are automatically created, pulled to the host machine and cleared from the test device. They are stored on the host machine in the configured [`resultsDir`](https://developer.android.com/studio/test/advanced-test-setup), which is `<path_to_your_project>/<module_name>/build/outputs/test-results/` by default.  

If you want to leave the diff images on your test device, you can exclude the `ClearScreenshotsTask` like so: 

```shell
./gradlew :<module_name>:connectedDebugAndroidTest --exclude-task :<module_name>:clearDebugAndroidTestScreenshots
```  
(or equivalent for your build variant.)
  
You'll be able to find the diff images on your test device in `/sdcard/Download/screenshots/`.  
  
Let me know if this answers your question.

**Comment by zhkvdm** [comment]
Hey there,
In additional to store diffs. Is it possible to store a captured screenshots and get it from device? Also if tests is success
