### ISSUE TITLE
New release for file path?

### ISSUE THREAD

**Issue by ceduliocezar** [dropbox/dropshots#56]
Hi, i was checking the issues and PRs and noticed that on May it was implemented the feature to specify the directory for the screenshots. However there was no release so far that includes such feature.

Issue: https://github.com/dropbox/dropshots/issues/24
PR: https://github.com/dropbox/dropshots/pull/35

The readme already includes the example with path parameter.

When is the release planned this?

**Comment by saket** [comment]
#35 was released with [0.4.1](https://github.com/dropbox/dropshots/blob/main/CHANGELOG.md#version-041)
