### ISSUE TITLE
Text signs are different at same emulators on different machines

### ISSUE THREAD

**Issue by zhkvdm** [dropbox/dropshots#63]
Letters and digits are different at the tests on local machine and on CI machine. Machines has a different proc architecture. Local machine is M1 arch. CI machine is Intel arch.
Zoomed diff image shows red pixels around the symbols.
Is symbols generating different depends on proc architecture?
How could i have the same screenshots at local and CI machines?

I can use tolerance for screenshots, but different screens contains a different amount of symbols. More symbols needs a large tolerance of screenshot. So I can't select the unique tolerance for every screen.
<img width="771" alt="Снимок экрана 2024-07-04 в 12 59 03" src="https://github.com/dropbox/dropshots/assets/47188147/a9b6ebe4-4ba9-43c8-86c5-2f4636d4aa9e">

**Comment by rharter** [comment]
Yes, this is one of the challenges that the [v|h]-shift from differ is meant to deal with. That is a pain, but another option is to [generate all screenshots in CI, committing them back into your PR for review](https://github.com/dropbox/dropshots/blob/main/.github/workflows/publish.yml#L175-L204) from there. I updated this repo to do that, based on something that was done in the Now in Android repository.
